-- ByAlee: esquema real para Supabase/PostgreSQL.
-- Ejecutar una sola vez en Supabase > SQL Editor.
-- Después crear el usuario administrador en Authentication > Users.

create extension if not exists pgcrypto;
create extension if not exists btree_gist;

create table if not exists public.studios (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  timezone text not null default 'America/Asuncion',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  studio_id uuid not null references public.studios(id) on delete cascade,
  full_name text not null default 'ByAlee',
  role text not null default 'admin' check (role in ('admin','professional')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.studio_settings (
  studio_id uuid primary key references public.studios(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  studio_id uuid not null references public.studios(id) on delete cascade,
  name text not null,
  category text not null default 'Pestañas',
  active boolean not null default true,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (studio_id, name)
);

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  studio_id uuid not null references public.studios(id) on delete cascade,
  full_name text not null,
  whatsapp text not null,
  phone_key text not null,
  birth_date date,
  birthday_marketing_consent boolean not null default false,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (studio_id, phone_key)
);

create table if not exists public.client_records (
  id bigint generated by default as identity primary key,
  studio_id uuid not null references public.studios(id) on delete cascade,
  client_id bigint not null references public.clients(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  unique (studio_id, client_id)
);

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  studio_id uuid not null references public.studios(id) on delete cascade,
  client_id bigint references public.clients(id) on delete set null,
  service_id bigint not null references public.services(id),
  date date not null,
  time time not null,
  start_minute integer not null check (start_minute between 0 and 1439),
  end_minute integer not null check (end_minute between 1 and 1800 and end_minute > start_minute),
  status text not null default 'requested' check (status in ('requested','pending','confirmed','completed','canceled','rejected','no_show')),
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_appointments_studio_date on public.appointments(studio_id, date);
create index if not exists idx_appointments_status on public.appointments(studio_id, status);

-- Evita que dos solicitudes activas ocupen el mismo rango incluso si llegan al mismo tiempo.
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'appointments_no_active_overlap'
  ) then
    alter table public.appointments
      add constraint appointments_no_active_overlap
      exclude using gist (
        studio_id with =,
        date with =,
        int4range(start_minute, end_minute, '[)') with &&
      ) where (status in ('requested','pending','confirmed'));
  end if;
end $$;

create table if not exists public.visits (
  id bigint generated by default as identity primary key,
  studio_id uuid not null references public.studios(id) on delete cascade,
  client_id bigint not null references public.clients(id) on delete cascade,
  service_id bigint references public.services(id) on delete set null,
  appointment_id bigint references public.appointments(id) on delete set null,
  date date not null,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.inventory_items (
  id bigint generated by default as identity primary key,
  studio_id uuid not null references public.studios(id) on delete cascade,
  name text not null,
  category text not null,
  priority text not null default 'professional' check (priority in ('professional','general')),
  stock numeric(12,2) not null default 0,
  minimum_stock numeric(12,2) not null default 0,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.availability_blocks (
  id bigint generated by default as identity primary key,
  studio_id uuid not null references public.studios(id) on delete cascade,
  date date not null,
  start_minute integer not null default 0,
  end_minute integer not null default 1440,
  all_day boolean not null default false,
  reason text,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_minute > start_minute)
);

create index if not exists idx_availability_studio_date on public.availability_blocks(studio_id, date);

-- Evita duplicados al volver a ejecutar los datos iniciales.
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'inventory_items_studio_name_key'
  ) then
    alter table public.inventory_items
      add constraint inventory_items_studio_name_key unique (studio_id, name);
  end if;
end $$;

create table if not exists public.media_files (
  id bigint generated by default as identity primary key,
  studio_id uuid not null references public.studios(id) on delete cascade,
  client_id bigint references public.clients(id) on delete cascade,
  visit_id bigint references public.visits(id) on delete cascade,
  appointment_id bigint references public.appointments(id) on delete cascade,
  kind text not null,
  storage_path text not null,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_media_client on public.media_files(studio_id, client_id);
create index if not exists idx_media_appointment on public.media_files(studio_id, appointment_id);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Crear triggers idempotentes.
do $$
declare
  table_name text;
  trigger_name text;
begin
  foreach table_name in array array['studios','profiles','studio_settings','services','clients','client_records','appointments','visits','inventory_items','availability_blocks']
  loop
    trigger_name := 'touch_' || table_name || '_updated_at';
    execute format('drop trigger if exists %I on public.%I', trigger_name, table_name);
    execute format('create trigger %I before update on public.%I for each row execute function public.touch_updated_at()', trigger_name, table_name);
  end loop;
end $$;

create or replace function public.is_studio_member(target_studio uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and studio_id = target_studio
      and active = true
  );
$$;

create or replace function public.current_studio_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select studio_id from public.profiles where id = auth.uid() and active = true limit 1;
$$;

grant execute on function public.is_studio_member(uuid) to authenticated;
grant execute on function public.current_studio_id() to authenticated;

grant usage on schema public to authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;
alter default privileges in schema public grant select, insert, update, delete on tables to authenticated;
alter default privileges in schema public grant usage, select on sequences to authenticated;

-- RLS: el navegador autenticado solo ve el estudio al que pertenece.
alter table public.studios enable row level security;
alter table public.profiles enable row level security;
alter table public.studio_settings enable row level security;
alter table public.services enable row level security;
alter table public.clients enable row level security;
alter table public.client_records enable row level security;
alter table public.appointments enable row level security;
alter table public.visits enable row level security;
alter table public.inventory_items enable row level security;
alter table public.availability_blocks enable row level security;
alter table public.media_files enable row level security;

-- Activa eventos en tiempo real para que las solicitudes aparezcan sin recargar.
alter table public.appointments replica identity full;
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'appointments'
  ) then
    alter publication supabase_realtime add table public.appointments;
  end if;
end $$;

drop policy if exists studios_member_select on public.studios;
create policy studios_member_select on public.studios for select to authenticated using (public.is_studio_member(id));

drop policy if exists profiles_own_studio on public.profiles;
create policy profiles_own_studio on public.profiles for select to authenticated using (id = auth.uid() or public.is_studio_member(studio_id));

drop policy if exists profiles_admin_update on public.profiles;
create policy profiles_admin_update on public.profiles for update to authenticated using (public.is_studio_member(studio_id)) with check (public.is_studio_member(studio_id));

-- Política común para tablas con studio_id.
do $$
declare
  table_name text;
  policy_name text;
begin
  foreach table_name in array array['studio_settings','services','clients','client_records','appointments','visits','inventory_items','availability_blocks','media_files']
  loop
    policy_name := table_name || '_member_all';
    execute format('drop policy if exists %I on public.%I', policy_name, table_name);
    execute format(
      'create policy %I on public.%I for all to authenticated using (public.is_studio_member(studio_id)) with check (public.is_studio_member(studio_id))',
      policy_name, table_name
    );
  end loop;
end $$;

-- Storage privado para comprobantes y fotografías.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'byalee-private',
  'byalee-private',
  false,
  5000000,
  array['image/jpeg','image/png','image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists byalee_storage_select on storage.objects;
create policy byalee_storage_select on storage.objects
for select to authenticated
using (
  bucket_id = 'byalee-private'
  and public.is_studio_member(((storage.foldername(name))[1])::uuid)
);

drop policy if exists byalee_storage_insert on storage.objects;
create policy byalee_storage_insert on storage.objects
for insert to authenticated
with check (
  bucket_id = 'byalee-private'
  and public.is_studio_member(((storage.foldername(name))[1])::uuid)
);

drop policy if exists byalee_storage_update on storage.objects;
create policy byalee_storage_update on storage.objects
for update to authenticated
using (
  bucket_id = 'byalee-private'
  and public.is_studio_member(((storage.foldername(name))[1])::uuid)
)
with check (
  bucket_id = 'byalee-private'
  and public.is_studio_member(((storage.foldername(name))[1])::uuid)
);

drop policy if exists byalee_storage_delete on storage.objects;
create policy byalee_storage_delete on storage.objects
for delete to authenticated
using (
  bucket_id = 'byalee-private'
  and public.is_studio_member(((storage.foldername(name))[1])::uuid)
);

-- Estudio y configuración inicial.
insert into public.studios (id, slug, name, timezone)
values ('00000000-0000-0000-0000-00000000ba1e', 'byalee', 'ByAlee', 'America/Asuncion')
on conflict (slug) do update set name = excluded.name, timezone = excluded.timezone;

insert into public.studio_settings (studio_id, data)
values (
  '00000000-0000-0000-0000-00000000ba1e',
  jsonb_build_object(
    'role','admin',
    'userName','ByAlee',
    'userEmail','',
    'studioName','ByAlee',
    'studioPhone','',
    'city','Luque',
    'openingTime','08:00',
    'closingTime','20:00',
    'slotInterval',30,
    'maintenanceDays',18,
    'defaultDeposit',50000,
    'currency','Gs.',
    'primaryColor','#8f5c70',
    'appearance','light',
    'bookingEnabled',true,
    'requireConsent',true,
    'autoOpenConfirmationWhatsApp',false,
    'allowOptionalBookingDetails',true,
    'allowDepositProof',true,
    'requireDepositChoice',true,
    'birthdayNotificationsEnabled',true,
    'birthdayNoticeDays',7,
    'birthdayMessageTemplate','Hola {nombre} 🎉 Se acerca tu cumpleaños. Desde {estudio} queremos prepararte algo especial. ¿Te gustaría conocer las promociones disponibles?',
    'requirePoliciesAcceptance',true,
    'bookingPoliciesVersion','1.0',
    'bookingPoliciesText','La cita queda confirmada únicamente cuando ByAlee la acepta. Si necesitás cancelar o reagendar, avisá con la mayor anticipación posible. La seña y su devolución se gestionan según el tiempo de aviso. Llegadas tardías pueden reducir el tiempo del servicio. ByAlee puede suspender la atención si detecta una condición que pueda afectar la seguridad del procedimiento.',
    'googleCalendarEnabled',false,
    'googleCalendarId','primary',
    'googleCalendarConnected',false,
    'timezone','America/Asuncion',
    'confirmationMessageTemplate','Hola {nombre} 😊 Tu cita de {servicio} fue confirmada para el {fecha} a las {hora}. Te esperamos en {estudio}.',
    'workDays',jsonb_build_array(1,2,3,4,5,6)
  )
)
on conflict (studio_id) do nothing;

-- Servicios generales de ejemplo. Luego se editan desde el panel.
insert into public.services (studio_id, name, category, active, data)
values
('00000000-0000-0000-0000-00000000ba1e','Clásicas','Pestañas',true,'{"name":"Clásicas","category":"Pestañas","duration":120,"prep":10,"cleanup":10,"price":150000,"color":"#A66C83","active":true,"description":"Aplicación clásica pelo a pelo."}'::jsonb),
('00000000-0000-0000-0000-00000000ba1e','Híbridas','Pestañas',true,'{"name":"Híbridas","category":"Pestañas","duration":150,"prep":10,"cleanup":10,"price":190000,"color":"#8F79A8","active":true,"description":"Combinación de técnica clásica y volumen."}'::jsonb),
('00000000-0000-0000-0000-00000000ba1e','Volumen ruso','Pestañas',true,'{"name":"Volumen ruso","category":"Pestañas","duration":180,"prep":15,"cleanup":15,"price":240000,"color":"#C08E45","active":true,"description":"Volumen personalizado según evaluación."}'::jsonb),
('00000000-0000-0000-0000-00000000ba1e','Lifting','Pestañas',true,'{"name":"Lifting","category":"Pestañas","duration":60,"prep":5,"cleanup":10,"price":120000,"color":"#5E8B7B","active":true,"description":"Elevación de pestañas naturales."}'::jsonb),
('00000000-0000-0000-0000-00000000ba1e','Perfilado de cejas','Cejas',true,'{"name":"Perfilado de cejas","category":"Cejas","duration":45,"prep":5,"cleanup":10,"price":70000,"color":"#9B7355","active":true,"description":"Diseño y perfilado de cejas."}'::jsonb),
('00000000-0000-0000-0000-00000000ba1e','Laminado de cejas','Cejas',true,'{"name":"Laminado de cejas","category":"Cejas","duration":75,"prep":10,"cleanup":10,"price":130000,"color":"#B3896A","active":true,"description":"Laminado y diseño de cejas."}'::jsonb),
('00000000-0000-0000-0000-00000000ba1e','Semipermanente manos','Manos',true,'{"name":"Semipermanente manos","category":"Manos","duration":90,"prep":10,"cleanup":10,"price":100000,"color":"#5E82A6","active":true,"description":"Esmaltado semipermanente en manos."}'::jsonb),
('00000000-0000-0000-0000-00000000ba1e','Semipermanente pies','Pies',true,'{"name":"Semipermanente pies","category":"Pies","duration":90,"prep":10,"cleanup":10,"price":110000,"color":"#6A93A9","active":true,"description":"Esmaltado semipermanente en pies."}'::jsonb)
on conflict (studio_id, name) do nothing;

insert into public.inventory_items (studio_id, name, category, priority, stock, minimum_stock, data)
values
('00000000-0000-0000-0000-00000000ba1e','Adhesivo Sensitive Pro','Adhesivos','professional',2,4,'{"name":"Adhesivo Sensitive Pro","category":"Adhesivos","priority":"professional","stock":2,"min":4,"unit":"unidades","location":"Carrito principal"}'::jsonb),
('00000000-0000-0000-0000-00000000ba1e','Parches de gel','Accesorios','professional',5,10,'{"name":"Parches de gel","category":"Accesorios","priority":"professional","stock":5,"min":10,"unit":"pares","location":"Cajón 1"}'::jsonb),
('00000000-0000-0000-0000-00000000ba1e','Desinfectante de superficies','Limpieza','general',3,2,'{"name":"Desinfectante de superficies","category":"Limpieza","priority":"general","stock":3,"min":2,"unit":"botellas","location":"Depósito"}'::jsonb)
on conflict (studio_id, name) do nothing;

-- Cada usuario creado desde Authentication queda asociado a ByAlee.
-- Recomendación: desactivar el registro público en Auth > Providers > Email.
create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, studio_id, full_name, role)
  values (
    new.id,
    '00000000-0000-0000-0000-00000000ba1e',
    coalesce(new.raw_user_meta_data ->> 'full_name', split_part(new.email, '@', 1), 'ByAlee'),
    'admin'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_auth_user();

-- Vincula también usuarios que ya existían antes de ejecutar este script.
insert into public.profiles (id, studio_id, full_name, role)
select
  id,
  '00000000-0000-0000-0000-00000000ba1e',
  coalesce(raw_user_meta_data ->> 'full_name', split_part(email, '@', 1), 'ByAlee'),
  'admin'
from auth.users
on conflict (id) do nothing;

update public.studio_settings
set data = data || jsonb_build_object(
  'sessionTimeoutEnabled', true,
  'sessionTimeoutMinutes', 30
)
where studio_id = '00000000-0000-0000-0000-00000000ba1e';

alter table public.profiles
add column if not exists username text;

create unique index if not exists profiles_username_unique
on public.profiles (lower(username))
where username is not null;

update public.profiles p
set
  username = 'byalee',
  full_name = 'ByAlee',
  updated_at = now()
from auth.users u
where p.id = u.id
  and lower(u.email) = lower('ecoronelcont@gmail.com');